name: Deploy React App

on:
  push:  # Run on every push to any branch
  pull_request:  # Run on every pull request

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test -- --passWithNoTests

    - name: Build React App
      run: npm run build

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'  # Only deploy if changes are pushed to 'main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
        token: ${{ secrets.GH_TOKEN }}
